### ISSUE TITLE
Alternative to pm2

### ISSUE THREAD

**Issue by vaibhav15s** [westy92/html-pdf-chrome#160]
Hi
Are there any alternatives to pm2?

**Comment by westy92** [comment]
If you are on Linux, you can likely use SystemD like this: https://expressjs.com/en/advanced/pm.html#systemd
Here's some potential options for Windows: https://www.raymond.cc/blog/keep-application-running-by-automatically-rerun-when-closed/

I'm sure there are plenty of others, but none that I have worked with.

Part of the reason I recommend pm2 is because it can be installed directly from npm.

**Comment by vaibhav15s** [comment]
Thanks for the update. pm2 is good but it has AGPL license. Google Cloud Platform will not accept products containing AGPLv3 code, according to their GCP license agreement.

**Comment by westy92** [comment]
Thank you for the info! Other users will find this helpful.
