### ISSUE TITLE
Completion triggers not working with Typekit Webfontloader

### ISSUE THREAD

**Issue by adamreisnz** [westy92/html-pdf-chrome#81]
I have tried various completion trigger mechanisms for hooking in typekit's webfontloader, but it doesn't want to work and keeps complaining that the trigger wasn't called.

In HTML template:

```html
<script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js"></script>
  <script type="text/javascript">
    WebFont.load({
      google: {families: ['Open+Sans:300,600']},
      active() {

        //Write to HTML to prove this event is called
        document.write("ACTIVE");

        //Tried with setting variable to true
        window.fontsLoadedFlag = true;

        //Tried with callback
        fontsLoaded();

        //Tried with event
        document.body.dispatchEvent(new Event('fontsLoaded'));
      },
    });
  </script>
```

Tried with callbacks:

```js
const {Callback} = htmlPdf.CompletionTrigger;
const completionTrigger = new Callback('fontsLoaded', 20000);
const options = {completionTrigger};
const pdf = await htmlPdf.create(html, options);
```

Tried with variable:

```js
const {Variable} = htmlPdf.CompletionTrigger;
const completionTrigger = new Variable('fontsLoadedFlag', 15000);
const options = {completionTrigger};
const pdf = await htmlPdf.create(html, options);
```

Tried with event:

```js
const {Event} = htmlPdf.CompletionTrigger;
const completionTrigger = new Event('fontsLoaded', 'body', 20000);
const options = {completionTrigger};
const pdf = await htmlPdf.create(html, options);
```

With the completion triggers, it just waits and waits until the timeout is reached and then errors that the trigger wasn't completed.

When I remove the completion trigger, I get a PDF generated with the word "ACTIVE", which proves that the event is called and the callback is triggered/variable is set.

However, html2pdf doesn't register the events. Any thoughts?

I've tried to use a simple timeout to call the completion trigger, and that works most of the time:

```js
setTimeout(() => fontsLoaded(), 5000);
```

**Comment by westy92** [comment]
Could you please provide your platform, Node.js version, and Chrome version?

**Comment by adamreisnz** [comment]
Yes sorry for not specifying, this is happening on OS X 10.11.5, Chrome 61.0.3163.100 (Official Build) (64-bit), Node 8.6.0

**Comment by westy92** [comment]
Could you please verify this is still an issue with the newly-published [v0.4.0](https://github.com/westy92/html-pdf-chrome/releases/tag/v0.4.0)?

**Comment by adamreisnz** [comment]
Yep still an issue with 0.4.0

**Comment by westy92** [comment]
I released v0.4.1, but that shouldn't have had an impact on this.

I tried to reproduce your issue by bundling the below code and adding it to the `html-pdf-chrome` [unit tests](https://github.com/westy92/html-pdf-chrome/blob/master/test/index.ts).
```typescript
it('#81', async () => {
  const html = `
    <html>
      <head>
        <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js"></script>
        <script type="text/javascript">
          WebFont.load({
            google: {
              families: ['Open Sans:300,600'],
            },
            active() {
              //Write to HTML to prove this event is called
              document.getElementById('test').innerHTML = 'Active!';

              //Tried with setting variable to true
              window.fontsLoadedFlag = true;

              //Tried with event
              document.body.dispatchEvent(new Event('fontsLoaded'));

              //Tried with callback
              fontsLoaded();
            },
          });
        </script>
      </head>
      <body>
        <div id="test" style="font-size: 180px; font-family: 'Open Sans';"></div>
      </body>
    </html>
  `;

  let result = await HtmlPdf.create(html, {
    port,
    completionTrigger: new HtmlPdf.CompletionTrigger.Callback('fontsLoaded', 20000),
  });
  await result.toFile('81/callback.pdf');

  result = await HtmlPdf.create(html, {
    port,
    completionTrigger: new HtmlPdf.CompletionTrigger.Variable('fontsLoadedFlag', 20000),
  });
  await result.toFile('81/variable.pdf');

  result = await HtmlPdf.create(html, {
    port,
    completionTrigger: new HtmlPdf.CompletionTrigger.Event('fontsLoaded', null, 20000),
  });
  await result.toFile('81/event.pdf');
});
```

After running the tests (`gulp`), it passed as expected:
![image](https://user-images.githubusercontent.com/290167/32479211-61b911ce-c34e-11e7-969e-98ca551a179d.png)
(downloading an _external_ JS library and font, rendering a page, printing to a PDF, and exporting to a file THRICE in 600ms...nice!)

I then verified the files, and as you can see, they generated correctly:
![image](https://user-images.githubusercontent.com/290167/32479252-849c6fb0-c34e-11e7-9eab-911b52a2d21a.png)

I then commented out `port,` in each set of options so that a fresh Chrome instance would be spawned, but the same (albeit slower) result was achieved:
![image](https://user-images.githubusercontent.com/290167/32479330-e5c971a2-c34e-11e7-90ca-2c4e4136a492.png)

**Notes:**
I had to move the `Event` dispatching above the `fontsLoaded()` call because it didn't seem to be returning.  Another potential fix for that is to place the callback within a `setTimeout()`:
```typescript
//Tried with callback
setTimeout(() => fontsLoaded(), 0);
```
If you look at [the source of the Event CompletionTrigger](https://github.com/westy92/html-pdf-chrome/blob/master/src/CompletionTrigger.ts#L82), the default `cssSelector` is `body` if none is specified, so you can ever so slightly optimize that:
```typescript
new HtmlPdf.CompletionTrigger.Event('fontsLoaded', null, 20000)
```

I tweaked your write-to-HTML code to help prove usage of the webfont.

Hopefully you'll be able to get things working with this example!  Please respond here either way if you have success or more failures.

**Comment by adamreisnz** [comment]
Thanks a lot for checking this out -- I'll dig in again and see if I can find what's happening.

**Comment by adamreisnz** [comment]
Looks like wrapping the callback in `setTimeout` does the trick, but I find that strange, why would that be necessary, since presumably the `active()` callback is already called asynchronously a fair bit of time after the callback is defined?

**Comment by westy92** [comment]
Here's the Callback CompletionTrigger code:
https://github.com/westy92/html-pdf-chrome/blob/314d6c736542499d996e110043b28e11d56ca1ac/src/CompletionTrigger.ts#L114-L125

**Comment by adamreisnz** [comment]
Is that executed after the HTML is loaded in the browser? That might explain this phenomenon, where the callback is called before it exists.

I ended up using the following code, with a fallback timeout to call the callback after 7.5 seconds just in case loading takes too long. This will prevent html2pdf from waiting too long:

```js
//Load font
    WebFont.load({
      google: {families: ['Open+Sans:300,600']},
      active() {
        setTimeout(() => {
          fontsLoaded();
        }, 0);
      },
    });

    //Guard against too long loading times
    setTimeout(() => {
      fontsLoaded();
    }, 7500);
```

Will close now since this timeout resolves the original problem. Will double check on my other machine just in case tomorrow.

**Comment by westy92** [comment]
That could be the case!  The CompletionTrigger code is executed after the page is navigated to and the load event fires.  Here's the relevant snippet:

https://github.com/westy92/html-pdf-chrome/blob/314d6c736542499d996e110043b28e11d56ca1ac/src/index.ts#L92-L103

**Comment by adamreisnz** [comment]
I see, yes that makes sense. Maybe worthwhile to document this potential issue somewhere in the readme. 👍
